trigger:
- main

pr: 
- none

pool:
  vmImage: 'windows-latest'

jobs:
- job: Checkout
  displayName: 'Checkout code'
  steps:
  - checkout: self

- job: RunTests
  displayName: 'Run automated tests'
  dependsOn: Checkout
  steps:
  - task: UseJavaVersion@0
    inputs:
      version: '11'
      addToPath: true

  - script: |
      ./gradlew clean test
    displayName: 'Run tests with Gradle'

- job: GenerateReports
  displayName: 'Generate reports'
  dependsOn: RunTests
  steps:
  - task: UseJavaVersion@0
    inputs:
      version: '11'
      addToPath: true

  - script: |
      ./gradlew aggregate
    displayName: 'Generate reports with Serenity'
