trigger:
- main

pr: 
- none

pool:
  vmImage: 'windows-latest'

jobs:
- job: Checkout
  displayName: 'Checkout code'
  steps:
  - checkout: self

- job: RunTests
  displayName: 'Run automated tests'
  dependsOn: Checkout
  steps:
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        # Set Java version
        $env:JAVA_HOME = "$(Agent.ToolsDirectory)\jdk\11.0.x"  # Update with the correct Java version
        $env:PATH = "$env:JAVA_HOME\bin;$env:PATH"

        # Display Java version
        java -version

        # Run Gradle task
        ./gradlew clean test
    displayName: 'Run tests with Gradle'

- job: GenerateReports
  displayName: 'Generate reports'
  dependsOn: RunTests
  steps:
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        # Set Java version
        $env:JAVA_HOME = "$(Agent.ToolsDirectory)\jdk\11.0.x"  # Update with the correct Java version
        $env:PATH = "$env:JAVA_HOME\bin;$env:PATH"

        # Display Java version
        java -version

        # Run Gradle task for generating reports
        ./gradlew aggregate
    displayName: 'Generate reports with Serenity'
