trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: Checkout
  displayName: 'Checkout code'
  steps:
  - checkout: self

- job: RunTests
  displayName: 'Run functional tests'
  steps:
  - task: Gradle@3
    inputs:
      gradleWrapperFile: 'gradlew'
      tasks: 'clean test aggregate'
      publishJUnitResults: true
      testResultsFiles: '**/target/site/serenity/*.xml'
      javaHomeOption: 'JDKVersion'
      sonarQubeRunAnalysis: false
      spotBugsAnalysis: false
    continueOnError: true

- job: GenerateReports
  displayName: 'Generate reports'
  dependsOn: RunTests
  steps:
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/TEST-*.xml'
      failTaskOnFailedTests: true

  - task: PublishBuildArtifacts@1
    inputs:
      artifactName: 'test-results'
      pathToPublish: '**/target/site/serenity'
