trigger:
- main

pr:
  branches:
    exclude:
    - '*'

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: CheckoutCode
  displayName: 'Checkout code'
  steps:
  - checkout: self

- job: RunAutomatedTests
  displayName: 'Run automated tests'
  dependsOn: CheckoutCode
  steps:
  - task: JavaToolInstaller@0
    inputs:
      versionSpec: "11"
      jdkArchitectureOption: x64
      jdkSourceOption: LocalDirectory
      jdkFile: "/builds/openjdk-11.0.2_linux-x64_bin.tar.gz"
      jdkDestinationDirectory: "/builds/binaries/externals"
      cleanDestinationDirectory: true

  - script: |
      ./gradlew clean test
    displayName: 'Run tests with Gradle'

- job: GenerateReports
  displayName: 'Generate reports'
  dependsOn: RunAutomatedTests
  steps:
  - task: JavaToolInstaller@0
    inputs:
      versionSpec: "11"
      jdkArchitectureOption: x64
      jdkSourceOption: LocalDirectory
      jdkFile: "/builds/openjdk-11.0.2_linux-x64_bin.tar.gz"
      jdkDestinationDirectory: "/builds/binaries/externals"
      cleanDestinationDirectory: true

  - script: |
      ./gradlew aggregate
    displayName: 'Generate reports with Gradle'
    
  - task: PublishTestResults@2
    displayName: 'Publish test results'
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/build/test-results/test/*.xml'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish artifacts'
    inputs:
      pathtoPublish: '**/target/site/serenity'
      artifactName: 'SerenityReports'
