trigger:
- main

pr:
  branches:
    exclude:
    - '*'

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: CheckoutCode
  displayName: 'Checkout code'
  steps:
  - checkout: self

- job: RunAutomatedTests
  displayName: 'Run automated tests'
  dependsOn: CheckoutCode
  steps:
  - task: UseDotNet@2
    displayName: 'Install JDK'
    inputs:
      version: '8.0'

  - script: |
      ./gradlew clean test
    displayName: 'Run tests with Gradle'

- job: GenerateReports
  displayName: 'Generate reports'
  dependsOn: RunAutomatedTests
  steps:
  - task: UseDotNet@2
    displayName: 'Install JDK'
    inputs:
      version: '8.0'

  - script: |
      ./gradlew aggregate
    displayName: 'Generate reports with Gradle'
    
  - task: PublishTestResults@2
    displayName: 'Publish test results'
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/build/test-results/test/*.xml'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish artifacts'
    inputs:
      pathtoPublish: '**/target/site/serenity'
      artifactName: 'SerenityReports'
